### ISSUE TITLE
repo sync --->ssh: connect to host 192.168.110.45 port 22: Connection refused

### ISSUE THREAD

**Issue by markKscode** [starfive-tech/meta-starfive#1]
root@947f02e4bcf8:~/starfive-yocto# repo sync
ssh: connect to host 192.168.110.45 port 22: Connection refused

**Comment by rebeccasf** [comment]
Resolved https://github.com/starfive-tech/meta-starfive/commit/07f42eabb7293428ba14b327bfa83326777f3a47
