### ISSUE TITLE
[starfive-visionfive2] u-boot-starfive fails to fetch

### ISSUE THREAD

**Issue by jwinarske** [starfive-tech/meta-starfive#2]
Two issues:
1. git fetcher protocol is set to git, should be `https`
2. commit needs to be updated, as it will fail to find the one specified.  A force push broke it?

**Comment by jwinarske** [comment]
There's this issue to:

`starfive-tool-native` appears to complete, only it fetches nothing, and does nothing.

It's using a private IP address for the fetch, which would never resolve.
```
https://github.com/starfive-tech/meta-starfive/blob/c9f5fc34921b0cf03e23e5af5d8d6e0fedc63050/recipes-bsp/starfive-tool/starfive-tool.bb#L14
```

**Comment by jwinarske** [comment]
after addressing these issues I can build `u-boot-starfive` for `starfive-visionfive2` without error.

**Comment by rebeccasf** [comment]
This issue has been addressed by this commit: https://github.com/starfive-tech/meta-starfive/commit/2b3c84c7231ca12bc7fad80c5e7bab2794de14b5
