### ISSUE TITLE
meta-starfive is not supported the machine as VisionFive2?

### ISSUE THREAD

**Issue by youngseok9497** [starfive-tech/meta-starfive#3]
meta-starfive is not supported the machine as VisionFive2?
It seems that VisionFive2 is still not supported when i look the setup.sh, so I am asking.
( I have tried to build by using setup.sh that modifying to use vf2() but do_compile of glib was failed.. )

**Comment by kuliga** [comment]
@youngseok9497 Why did you decide to close it?  I've come across the very same issue and wonder whether you've made any progress on it.
